# Generated by Django 2.0 on 2017-12-18 21:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.domain.game.entity.code
import src.domain.game.entity.codePeg
import src.domain.game.entity.feedback
import src.domain.game.entity.game
import src.domain.game.entity.historicEntry


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoCode',
            fields=[
                ('_id', models.UUIDField(db_column='id', editable=False, primary_key=True, serialize=False, unique=True)),
                ('_created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'game_codes',
            },
            bases=(src.domain.game.entity.code.Code, models.Model),
        ),
        migrations.CreateModel(
            name='DjangoCodeCodePeg',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('_code', models.ForeignKey(db_column='djangocode_id', on_delete=django.db.models.deletion.CASCADE, to='games.DjangoCode')),
            ],
            options={
                'db_table': 'game_codes__code_pegs',
            },
        ),
        migrations.CreateModel(
            name='DjangoCodePeg',
            fields=[
                ('_id', models.UUIDField(db_column='id', editable=False, primary_key=True, serialize=False, unique=True)),
                ('_created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, editable=False)),
                ('_color_value', models.TextField(db_column='color')),
            ],
            options={
                'db_table': 'game_code_pegs',
            },
            bases=(src.domain.game.entity.codePeg.CodePeg, models.Model),
        ),
        migrations.CreateModel(
            name='DjangoFeedback',
            fields=[
                ('_id', models.UUIDField(db_column='id', editable=False, primary_key=True, serialize=False, unique=True)),
                ('_created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, editable=False)),
                ('_black_pegs', models.IntegerField(db_column='black_pegs')),
                ('_white_pegs', models.IntegerField(db_column='white_pegs')),
            ],
            options={
                'db_table': 'game_feedbacks',
            },
            bases=(src.domain.game.entity.feedback.Feedback, models.Model),
        ),
        migrations.CreateModel(
            name='DjangoGame',
            fields=[
                ('_id', models.UUIDField(db_column='id', editable=False, primary_key=True, serialize=False, unique=True)),
                ('_created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, editable=False)),
                ('_code', models.ForeignKey(db_column='code_id', on_delete=django.db.models.deletion.CASCADE, to='games.DjangoCode')),
            ],
            options={
                'db_table': 'games',
            },
            bases=(src.domain.game.entity.game.Game, models.Model),
        ),
        migrations.CreateModel(
            name='DjangoHistoricEntry',
            fields=[
                ('_id', models.UUIDField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('_created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, editable=False)),
                ('_code_guess', models.ForeignKey(db_column='code_guess_id', on_delete=django.db.models.deletion.DO_NOTHING, to='games.DjangoCode')),
                ('_feedback', models.ForeignKey(db_column='feedback_id', on_delete=django.db.models.deletion.DO_NOTHING, to='games.DjangoFeedback')),
                ('_game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.DO_NOTHING, to='games.DjangoGame')),
            ],
            options={
                'db_table': 'game_historic_entries',
            },
            bases=(src.domain.game.entity.historicEntry.HistoricEntry, models.Model),
        ),
        migrations.AddField(
            model_name='djangocodecodepeg',
            name='_code_peg',
            field=models.ForeignKey(db_column='djangocodepeg_id', on_delete=django.db.models.deletion.CASCADE, to='games.DjangoCodePeg'),
        ),
        migrations.AddField(
            model_name='djangocode',
            name='_code_pegs',
            field=models.ManyToManyField(db_column='code_pegs', through='games.DjangoCodeCodePeg', to='games.DjangoCodePeg'),
        ),
    ]
